apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hellos.extension.example.com
spec:
  group: extension.example.com
  version: v1
  scope: Namespaced
  names:
    plural: hellos
    singular: hello
    kind: Hello